Repository GoogleChrome/chrome-extensions-samples, pull requests merged in 2023-01, with the labels that each got.

#799 Removes duplicate legacy hello-world
  examples/hello-world/background.js
  examples/hello-world/hello.html
  examples/hello-world/manifest.json
Labels: bug

#808 Fix typo in focus-mode ext description
  tutorials/focus-mode/manifest.json
Labels: cla: yes

#792 Convert MV2 optional permission example to MV3
  examples/optional_permissions/README.md
  examples/optional_permissions/images/icon128.png
  examples/optional_permissions/images/icon16.png
  examples/optional_permissions/images/icon32.png
  examples/optional_permissions/images/icon48.png
  examples/optional_permissions/manifest.json
  examples/optional_permissions/newtab.html
  examples/optional_permissions/newtab.js
  examples/optional_permissions/style.css
Labels: API usage

#806 Split favicon into two separate examples
  api/favicon/content.html
  api/favicon/content.js
  api/favicon/manifest.json
  api/favicon/popup.html
  api/favicon/popup.js
  examples/favicon-cs/README.md
  examples/favicon-cs/content.js
  examples/favicon-cs/manifest.json
  examples/favicon-cs/style.css
Labels: API usage
